theme: jekyll-theme-minimal
title: Pagar.Me SDK (.NET)
description: The Pagar.Me SDK for .NET projects
logo: https://raw.githubusercontent.com/guibranco/PagarMe-SDK-dotnet/master/packageLogo.png
show_downloads: true
